<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E216LTRV" ignored="0" name="Rest 04" tests="1" failures="1" timestamp="05 Oct 2018 09:55:38 GMT" time="4.609" errors="0">
  <testcase name="checkpostmethod" time="3.654" classname="APITest.rest.checkpost">
    <failure type="java.lang.AssertionError" message="expected [201] but found [415]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [415]
	at APITest.rest.checkpost.checkpostmethod(checkpost.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- checkpostmethod -->
</testsuite> <!-- Rest 04 -->
